[package]
name = "flag"
version = "1.0.1"
authors = ["matt.limb17@gmail.com <matt.limb17@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
colored_truecolor = "0.1.0"
clap = "2.33.0"